#! /bin/sh

~/bin/wp-load

compton &

sxhkd &
$HOME/.config/polybar/launch.sh
xrdb -merge ~/.Xresources

bspc config border_width		4
bspc config window_gap			12

bspc config split_ratio			0.50
bspc config borderless_monocle	true
bspc config gapless_monocle		true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config automatic_scheme	longest_side

bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

bspc config focused_border_color "#811919"

if [ "$(hostname)" = "VahRuta" ]; then
	bspc monitor DisplayPort-0 -d 1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9 1-10 1-11 1-12 1-13 1-14 1-15 1-16 1-17 1-18 1-19 1-20
	bspc monitor DisplayPort-1 -d 2-1 2-2 2-3 2-4 2-5 2-6 2-7 2-8 2-9 2-10 2-11 2-12 2-13 2-14 2-15 2-16 2-17 2-18 2-19 2-20
	bspc monitor HDMI-A-0 -d 3-1 3-2 3-3 3-4 3-5 3-6 3-7 3-8 3-9 3-10 3-11 3-12 3-13 3-14 3-15 3-16 3-17 3-18 3-19 3-20

	bspc wm --reorder-monitors DisplayPort-0 DisplayPort-1 HDMI-A-0

	#bspc rule -a Gimp desktop='4-1' state=floating follow=on
	bspc rule -a steam desktop='2-20' follow=on
	bspc rule -a zoom desktop='2-19' follow=on

	steam &

elif [ "$(hostname)" = "moblin" ]; then
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
fi
