input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = true
    rounding = 15

    position = 0, -80
    halign = center
    valign = center
}

background {
    monitor = 

    # Image
    path = /home/trevor/git_repos/personal/wallpapers/mn/stone_arch_bridge_night.jpg
    #path = screenshot

    # Blur
    blur_passes = 2
    blur_size = 2

    # Fallback when image not present
    color = rgba(25, 20, 20, 1.0)
}

label {
  monitor =

  text = Welcome back, $USER
  font_size = 32

  halign = center
  valign = center
  position = 0, 0
}

label {
  monitor =

  text = $TIME
  font_size = 18
  
  halign = center
  valign = top
  position = 0, -20
}
