
#import = ["~/.config/alacritty/colors/solarized_dark.toml"]
general.import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
opacity = 0.99

[font]
size = 14.0

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"
