# Be aware of version control systems and display information.
set vcs_aware true

# Use one of the supported image preview protocols
set preview_images true

# Which colorscheme to use?  These colorschemes are available by default:
# default, jungle, snow, solarized
set colorscheme solarized

# Draw borders around columns
set draw_borders true

# Use fuzzy tab completion with the "cd" command
set cd_tab_fuzzy true

# Enable scroll wrapping
set wrap_scroll true
